### ISSUE TITLE
Elasticsearch: Speed  Up  Some  Highlighting 

### ISSUE THREAD

**Issue by sdabhi23** [elastic/gsoc#10]
Hey,

I want to contribute to Elasticsearch and take up **Speed  Up  Some  Highlighting**.

Considering that I have knowledge of JAVA and a very little experience of using Elasticsearch, can you please guide me?

Regards,
Shrey Dabhi
(sdabhi23)

**Comment by xeraa** [comment]
As described in the readme the two most important points for your application are:

1. A PR for the project you want to be working on.
2. A good proposal on what you want to do exactly in those 3 months.

If you have any other general questions, please post them in https://discuss.elastic.co/c/elastic-community/elastic-gsoc

**Comment by xeraa** [comment]
Closing since the discussion has shifted to https://discuss.elastic.co/t/gsoc-elasticsearch-speed-up-some-highlighting/122069/8 (which is also the right place for any further questions around this)
