### ISSUE TITLE
GSOC-18 Project

### ISSUE THREAD

**Issue by aksh98** [elastic/gsoc#13]
Hi
I am willing to work on the Machine Learning technologies newly introduced in Elasticsearch. Is there any ongoing project I can contribute to which can be added as a project in GSOC-18?

Thanks and regards
Akarsha

**Comment by xeraa** [comment]
Great question!

[Rule 1.26](https://summerofcode.withgoogle.com/rules/) defines:

> “Project” means an open source coding project to be worked on by a Student as an individual.

Generally code most be released under an [Open Source Initiative (OSI)-approved license](https://opensource.org/licenses), which the X-Pack features won't be. So the Machine Learning code will be off limits for GSoC unfortunately.

While we are currently not running any internship programs, we are hiring. So if you are interested in a full-time position, let me know and we can discuss further (on a non-public channel).

**Comment by aksh98** [comment]
Isn't the X-pack going opensource? (As announced by Shay in ElasticON'18)

**Comment by xeraa** [comment]
This is unfortunately a common misunderstanding, which we are [trying to address](https://www.elastic.co/products/x-pack/open). It will be open code, but you will still require a commercial license to use it in production. We are currently working on that license, but it won't be one of the OSI-approved ones.

**Comment by aksh98** [comment]
Thanks for the clarification. :)
I guess I need to choose one of the existing projects then !
