### ISSUE TITLE
Logstash: Java Plugin API GSOC 18

### ISSUE THREAD

**Issue by isaeef** [elastic/gsoc#17]
I want to contribute to the project Java Plugin. I have  experience in developing in Java language and has knowledge about logstash.Can we discuss about this project @yaauie @logmonster

**Comment by isaeef** [comment]
From what I understand from the Issue #9227
Here are the Few things that I like to work on the project 
1.Port Logstash plugins from the repo-logstash-plugins
2.Change Design Pattern to low dependency on logstash core with the logstash plugins
3.work around for the automatic update of plugins with elastic core

**Comment by xeraa** [comment]
Hey @isaeef,

Have you seen the discussion at https://discuss.elastic.co/t/contributing-to-logstash/120290/7 (especially the last 2 posts)? Generally the main goal is to work with the new API and find potential problems + suggest improvements.

Could you elaborate a little further around your plans for points 2. and 3.? I'm not sure those are really within the scope of this project.

**Comment by xeraa** [comment]
Closing since the application period has finished. We can start a new discussion as needed.
