### ISSUE TITLE
Applying for mentoring in GSoC

### ISSUE THREAD

**Issue by SanketDG** [elastic/gsoc#23]
Not sure if this is the right place, but I'd like to apply as a mentor for this year's GSOC.

I previously mentored for the [coala](https://coala.io/) organization in [2017](https://summerofcode.withgoogle.com/archive/2017/projects/6645955352854528/).

Is there any process for the application of a mentor? I understand the most primary requirement would be some amount of familiarity with the codebase, but there are still two months left for the program to start.

**Comment by xeraa** [comment]
Thanks for the offer! But we should have enough mentors from the core team (3 to 4 people and I only expect 2 or maybe 3 projects to happen), though of course we always love contributions :)
