### ISSUE TITLE
GraphQL?

### ISSUE THREAD

**Issue by the4thfloor** [elastic/gsoc#5]
Hello,

I am not a student and use Elasticsearch only for a small private project.

In my project I want to integrate GraphQL into Elasticsearch. I have found this discussion, but I am not sure whether arisbanach is working on it (https://discuss.elastic.co/t/graphql-integration/112102/3).

My background: Java developer since 2007, currently senior mobile app developer (Android, iOS, Flutter)

Ralph

**Comment by xeraa** [comment]
I'm afraid that only students qualify for Google Summer of Code.

If you are interesting in accessing Elasticsearch through GraphQL you might be interested in https://github.com/graphql-compose/graphql-compose-elasticsearch (no affiliation from our side, but it's the closest I've seen). Hope that helps :)
