### ISSUE TITLE
Invalid link of GSoC discussion group

### ISSUE THREAD

**Issue by mr1holmes** [elastic/gsoc#8]
Change to
https://discuss.elastic.co/c/elastic-community/elastic-gsoc

**Comment by aravindputrevu** [comment]
The link works for me @mr1holmes . Could you please elaborate on the issue?

**Comment by mr1holmes** [comment]
The link that is provided on the page is https://discuss.elastic.co/c/elastic-user-groups/elastic-gsoc.

**Comment by xeraa** [comment]
@mr1holmes thanks for that! We did rename that section on discuss and I forgot to update the link.
